# make environment
PYTHON = /usr/local/bin/python
ECHO = echo

# directories

# documentation source
DOCDIR = docsrc

# build directory
BUILDDIR = build

# built html documentation directory
HTMLDIR = html

# built pdf documentation directory
PDFDIR = .
